name: Bento
filename: bento.js
description: Tightly pack your content
license: Public domain, http://unlicense.org
copyright: Yaroslaff Fedin
author: inviz
category: Interface
current: 0.2
sources:
  - Source/Bento.js